### PR TITLE
Bump or-tools to v7.8

### PR DESCRIPTION
**Pull request by senhalil**
Validated by massive test on 20201218

### CODE REVIEW

**Comment by senhalil** [comment]
@alain-andre  is there anything else I need to change to pass from or-tools 7.5 to 7.8? I assume the image is going to be generated and added to the registry automatically one this PR is merged, right?

**Review by fonsecadeline — APPROVED** [review]

**Comment by alain-andre** [comment]
Yes @senhalil this all you need to change. When you will push the tag, the docker image will be generated and pushed to our registry so you will be able to use it in optimizer-api.

**Comment by senhalil** [comment]
> When you will push the tag, the docker image will be generated and pushed to our registry so you will be able to use it in optimizer-api.

How I can push a tag on the repo of Mapotempo?

**Comment by alain-andre** [comment]
> > When you will push the tag, the docker image will be generated and pushed to our registry so you will be able to use it in optimizer-api.
> 
> How I can push a tag on the repo of Mapotempo?

You can do it as a member of the group.

**Pull request merged**
