### PR TITLE
Move to passenger-ruby25 

### PR DESCRIPTION
**Pull request by alain-andre**
Base build on phusion/passenger-ruby25 to avoid errors in optimizer-api due to Debian and Ubuntu lib differences.

### CODE REVIEW

**Comment by senhalil** [comment]
@alain-andre this will not bite us later because google publishes pre-compiled or-tool libraries only for selected OS's (debien10, fedora33, ubuntu18/20, centos8, etc.), right?

**Comment by alain-andre** [comment]
@senhalil The phusion/passenger-ruby25 image is based on the latest Ubuntu, so I don't thing there would be a problem. And even if there was an incompatibility the test during the build would spit out.

**Comment by senhalil** [comment]
@alain-andre we have a problem on the optim-api side, we suspect it is because of this PR. You changed the OS of optim-ortools but the OS of optim-api stayed the same so the copy oeration fails
https://travis-ci.com/github/Mapotempo/optimizer-api/builds/208753513#L555

**Comment by alain-andre** [comment]
@senhalil yes I'have seen it. Until this [MR](https://github.com/Mapotempo/optimizer-api/pull/45) is accepted, the docker test in optimizer-api will fail.

**Comment by senhalil** [comment]
@alain-andre  if that PR is going to take longer, can we separate the necessary part in another PR, would it take long? Because that PR is already doing lots and it looks like it is going to take a while to finalize. What do you think?

**Pull request merged**
